version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    networks:
      - net
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "test"
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - net
networks:
  net:
volumes:
  app:
